# Generated by Django 3.2.9 on 2021-11-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='fecha_criacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Criação'),
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='livro',
            name='autor_id',
            field=models.ManyToManyField(to='livro.Autor'),
        ),
    ]
