# Generated by Django 3.2.9 on 2021-11-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_auto_20211121_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='fecha_criacao',
            new_name='data_criacao',
        ),
    ]
