# Generated by Django 3.2.9 on 2021-11-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_auto_20211130_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='livro',
            name='autor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.autor'),
            preserve_default=False,
        ),
    ]
